// AUTO-GERADO por scripts/gerar_realdata_frontend.py
// Dados reais derivados dos 4 Parquets anonimizados (SMS-Rio Hackathon 2026)
// Score PRIO-ACS conforme MASTER_CONTEXT.md secao 6.4
// Para regerar: python scripts/gerar_realdata_frontend.py
//
// Para usar no app, troque o import em ListaPage.tsx e VisitaPage.tsx:
//   - import { ... } from '../mockData'
//   + import { ... } from '../realData'

import type { Paciente } from './types'

// Equipe demo: 54221d7b (centroide da unidade de saúde)
export const EQUIPE_LAT = -22.939472
export const EQUIPE_LNG = -43.252141

export const REAL_PACIENTES: Paciente[] = [
  {
    id: 'p-062cb0',
    nome: 'Daniel O.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '66+',
    sexo: 'Masculino',
    racaCor: 'Parda',
    situacaoVulnerabilidade: true,
    lat: -22.972343, lng: -43.284011,
    distanciaKm: 4.9,
    enderecoDescricao: '4,9 km da unidade',
    hipertenso: true, diabetico: true, gestante: false,
    condicoes: ['diabetico', 'hipertenso', 'vulneravel'],
    prioridade: 'critica', prioScore: 75,
    motivoPrioridade: 'hipertenso + diabético · idoso 66+ · vulnerável',
    ultimaVisita: '2025-10-30',
  },
  {
    id: 'p-ae6a9f',
    nome: 'Camila N.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '66+',
    sexo: 'Feminino',
    racaCor: 'Parda',
    situacaoVulnerabilidade: true,
    lat: -22.975084, lng: -43.284404,
    distanciaKm: 5.2,
    enderecoDescricao: '5,2 km da unidade',
    hipertenso: true, diabetico: true, gestante: false,
    condicoes: ['diabetico', 'hipertenso', 'vulneravel'],
    prioridade: 'critica', prioScore: 75,
    motivoPrioridade: 'hipertenso + diabético · idoso 66+ · vulnerável',
    ultimaVisita: '2025-10-20',
  },
  {
    id: 'p-cb460d',
    nome: 'Luciana N.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '45-65',
    sexo: 'Feminino',
    racaCor: 'Parda',
    situacaoVulnerabilidade: true,
    lat: -22.918356, lng: -43.370644,
    distanciaKm: 12.4,
    enderecoDescricao: '12,4 km da unidade',
    hipertenso: true, diabetico: true, gestante: false,
    condicoes: ['diabetico', 'hipertenso', 'vulneravel'],
    prioridade: 'critica', prioScore: 75,
    motivoPrioridade: 'hipertenso + diabético · vulnerável',
    ultimaVisita: '2025-11-24',
  },
  {
    id: 'p-ec7361',
    nome: 'Thiago V.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '66+',
    sexo: 'Masculino',
    racaCor: 'Parda',
    situacaoVulnerabilidade: true,
    lat: -22.976989, lng: -43.282556,
    distanciaKm: 5.2,
    enderecoDescricao: '5,2 km da unidade',
    hipertenso: true, diabetico: true, gestante: false,
    condicoes: ['diabetico', 'hipertenso', 'vulneravel'],
    prioridade: 'critica', prioScore: 70,
    motivoPrioridade: 'hipertenso + diabético · idoso 66+ · vulnerável · sem visita há 121d',
    ultimaVisita: '2025-09-01',
  },
  {
    id: 'p-a461d5',
    nome: 'Antonio B.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '66+',
    sexo: 'Masculino',
    racaCor: 'Parda',
    situacaoVulnerabilidade: true,
    lat: -22.976101, lng: -43.283491,
    distanciaKm: 5.2,
    enderecoDescricao: '5,2 km da unidade',
    hipertenso: true, diabetico: true, gestante: false,
    condicoes: ['diabetico', 'hipertenso', 'vulneravel'],
    prioridade: 'critica', prioScore: 70,
    motivoPrioridade: 'hipertenso + diabético · idoso 66+ · vulnerável · sem visita há 126d',
    ultimaVisita: '2025-08-27',
  },
  {
    id: 'p-fa6305',
    nome: 'Claudia S.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '19-45',
    sexo: 'Feminino',
    racaCor: 'Preta',
    situacaoVulnerabilidade: true,
    lat: -22.976625, lng: -43.284329,
    distanciaKm: 5.3,
    enderecoDescricao: '5,3 km da unidade',
    hipertenso: false, diabetico: false, gestante: true,
    condicoes: ['gestante', 'vulneravel'],
    prioridade: 'critica', prioScore: 70,
    motivoPrioridade: 'gestante · vulnerável · 2 urgência/internação',
    ultimaVisita: '2025-12-24',
  },
  {
    id: 'p-220ee6',
    nome: 'Ana V.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '45-65',
    sexo: 'Feminino',
    racaCor: 'Branca',
    situacaoVulnerabilidade: true,
    lat: -22.912507, lng: -43.226092,
    distanciaKm: 4.0,
    enderecoDescricao: '4,0 km da unidade',
    hipertenso: true, diabetico: true, gestante: false,
    condicoes: ['diabetico', 'hipertenso', 'vulneravel'],
    prioridade: 'critica', prioScore: 70,
    motivoPrioridade: 'hipertenso + diabético · vulnerável · sem visita há 121d',
    ultimaVisita: '2025-09-01',
  },
  {
    id: 'p-6e1e27',
    nome: 'Rafael T.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '66+',
    sexo: 'Masculino',
    racaCor: 'Branca',
    situacaoVulnerabilidade: true,
    lat: -22.918302, lng: -43.370101,
    distanciaKm: 12.3,
    enderecoDescricao: '12,3 km da unidade',
    hipertenso: true, diabetico: true, gestante: false,
    condicoes: ['diabetico', 'hipertenso', 'vulneravel'],
    prioridade: 'critica', prioScore: 70,
    motivoPrioridade: 'hipertenso + diabético · idoso 66+ · vulnerável · sem visita há 147d',
    ultimaVisita: '2025-08-06',
  },
  {
    id: 'p-cbdfb3',
    nome: 'Carla R.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '66+',
    sexo: 'Feminino',
    racaCor: 'Preta',
    situacaoVulnerabilidade: true,
    lat: -22.960513, lng: -43.272662,
    distanciaKm: 3.1,
    enderecoDescricao: '3,1 km da unidade',
    hipertenso: true, diabetico: true, gestante: false,
    condicoes: ['diabetico', 'hipertenso', 'vulneravel'],
    prioridade: 'critica', prioScore: 70,
    motivoPrioridade: 'hipertenso + diabético · idoso 66+ · vulnerável · nunca visitado',
    ultimaVisita: null,
  },
  {
    id: 'p-80df1d',
    nome: 'Carla D.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '19-45',
    sexo: 'Feminino',
    racaCor: 'Branca',
    situacaoVulnerabilidade: true,
    lat: -22.965923, lng: -43.278747,
    distanciaKm: 4.0,
    enderecoDescricao: '4,0 km da unidade',
    hipertenso: false, diabetico: false, gestante: true,
    condicoes: ['gestante', 'vulneravel'],
    prioridade: 'alta', prioScore: 65,
    motivoPrioridade: 'gestante · vulnerável · 2 urgência/internação · sem visita há 100d',
    ultimaVisita: '2025-09-22',
  },
  {
    id: 'p-66cdfb',
    nome: 'Eliane I.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '19-45',
    sexo: 'Feminino',
    racaCor: 'Parda',
    situacaoVulnerabilidade: false,
    lat: -22.973862, lng: -43.283134,
    distanciaKm: 5.0,
    enderecoDescricao: '5,0 km da unidade',
    hipertenso: true, diabetico: false, gestante: true,
    condicoes: ['gestante', 'hipertenso'],
    prioridade: 'alta', prioScore: 65,
    motivoPrioridade: 'gestante hipertensa · nunca visitado',
    ultimaVisita: null,
  },
  {
    id: 'p-c520fb',
    nome: 'Mariana G.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '19-45',
    sexo: 'Feminino',
    racaCor: 'Preta',
    situacaoVulnerabilidade: true,
    lat: -22.976225, lng: -43.277354,
    distanciaKm: 4.8,
    enderecoDescricao: '4,8 km da unidade',
    hipertenso: true, diabetico: true, gestante: false,
    condicoes: ['diabetico', 'hipertenso', 'vulneravel'],
    prioridade: 'alta', prioScore: 60,
    motivoPrioridade: 'hipertenso + diabético · vulnerável · 2 urgência/internação',
    ultimaVisita: '2025-10-25',
  },
  {
    id: 'p-75f6a5',
    nome: 'Fernanda B.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '45-65',
    sexo: 'Feminino',
    racaCor: 'Branca',
    situacaoVulnerabilidade: true,
    lat: -22.974378, lng: -43.284295,
    distanciaKm: 5.1,
    enderecoDescricao: '5,1 km da unidade',
    hipertenso: true, diabetico: true, gestante: false,
    condicoes: ['diabetico', 'hipertenso', 'vulneravel'],
    prioridade: 'alta', prioScore: 60,
    motivoPrioridade: 'hipertenso + diabético · vulnerável',
    ultimaVisita: '2025-12-13',
  },
  {
    id: 'p-5c6e9b',
    nome: 'Henrique H.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '66+',
    sexo: 'Masculino',
    racaCor: 'Branca',
    situacaoVulnerabilidade: false,
    lat: -22.975025, lng: -43.285206,
    distanciaKm: 5.2,
    enderecoDescricao: '5,2 km da unidade',
    hipertenso: true, diabetico: true, gestante: false,
    condicoes: ['diabetico', 'hipertenso'],
    prioridade: 'alta', prioScore: 60,
    motivoPrioridade: 'hipertenso + diabético · idoso 66+ · 3 urgência/internação',
    ultimaVisita: '2025-12-20',
  },
  {
    id: 'p-879b11',
    nome: 'Ana H.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '0-6',
    sexo: 'Feminino',
    racaCor: 'Parda',
    situacaoVulnerabilidade: true,
    lat: -22.975315, lng: -43.284328,
    distanciaKm: 5.2,
    enderecoDescricao: '5,2 km da unidade',
    hipertenso: false, diabetico: false, gestante: false,
    condicoes: ['vulneravel', 'crianca'],
    prioridade: 'alta', prioScore: 60,
    motivoPrioridade: 'criança 0-6 · vulnerável · sem visita há 144d',
    ultimaVisita: '2025-08-09',
  },
  {
    id: 'p-083ba4',
    nome: 'Anderson F.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '0-6',
    sexo: 'Masculino',
    racaCor: 'Parda',
    situacaoVulnerabilidade: true,
    lat: -22.917922, lng: -43.370013,
    distanciaKm: 12.3,
    enderecoDescricao: '12,3 km da unidade',
    hipertenso: false, diabetico: false, gestante: false,
    condicoes: ['vulneravel', 'crianca'],
    prioridade: 'alta', prioScore: 60,
    motivoPrioridade: 'criança 0-6 · vulnerável · 7 urgência/internação · sem visita há 225d',
    ultimaVisita: '2025-05-20',
  },
  {
    id: 'p-d842de',
    nome: 'Vanessa I.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '45-65',
    sexo: 'Feminino',
    racaCor: 'Parda',
    situacaoVulnerabilidade: false,
    lat: -22.918234, lng: -43.370021,
    distanciaKm: 12.3,
    enderecoDescricao: '12,3 km da unidade',
    hipertenso: true, diabetico: true, gestante: false,
    condicoes: ['diabetico', 'hipertenso'],
    prioridade: 'alta', prioScore: 60,
    motivoPrioridade: 'hipertenso + diabético',
    ultimaVisita: '2025-12-23',
  },
  {
    id: 'p-0f6980',
    nome: 'Gustavo L.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '66+',
    sexo: 'Masculino',
    racaCor: 'Parda',
    situacaoVulnerabilidade: false,
    lat: -22.972899, lng: -43.282581,
    distanciaKm: 4.9,
    enderecoDescricao: '4,9 km da unidade',
    hipertenso: true, diabetico: true, gestante: false,
    condicoes: ['diabetico', 'hipertenso'],
    prioridade: 'alta', prioScore: 60,
    motivoPrioridade: 'hipertenso + diabético · idoso 66+',
    ultimaVisita: '2025-12-05',
  },
  {
    id: 'p-f8b99e',
    nome: 'Daniel V.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '66+',
    sexo: 'Masculino',
    racaCor: 'Branca',
    situacaoVulnerabilidade: false,
    lat: -22.973806, lng: -43.284228,
    distanciaKm: 5.0,
    enderecoDescricao: '5,0 km da unidade',
    hipertenso: true, diabetico: true, gestante: false,
    condicoes: ['diabetico', 'hipertenso'],
    prioridade: 'alta', prioScore: 60,
    motivoPrioridade: 'hipertenso + diabético · idoso 66+ · 7 urgência/internação',
    ultimaVisita: '2025-11-05',
  },
  {
    id: 'p-b4d08a',
    nome: 'Larissa B.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '45-65',
    sexo: 'Feminino',
    racaCor: 'Branca',
    situacaoVulnerabilidade: true,
    lat: -22.975612, lng: -43.285407,
    distanciaKm: 5.3,
    enderecoDescricao: '5,3 km da unidade',
    hipertenso: true, diabetico: true, gestante: false,
    condicoes: ['diabetico', 'hipertenso', 'vulneravel'],
    prioridade: 'alta', prioScore: 60,
    motivoPrioridade: 'hipertenso + diabético · vulnerável · 2 urgência/internação',
    ultimaVisita: '2025-12-26',
  },
  {
    id: 'p-24117a',
    nome: 'Helena F.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '66+',
    sexo: 'Feminino',
    racaCor: 'Branca',
    situacaoVulnerabilidade: false,
    lat: -22.974321, lng: -43.283632,
    distanciaKm: 5.0,
    enderecoDescricao: '5,0 km da unidade',
    hipertenso: true, diabetico: true, gestante: false,
    condicoes: ['diabetico', 'hipertenso'],
    prioridade: 'alta', prioScore: 60,
    motivoPrioridade: 'hipertenso + diabético · idoso 66+ · 11 urgência/internação',
    ultimaVisita: '2025-12-18',
  },
  {
    id: 'p-8f9e60',
    nome: 'Fernanda N.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '45-65',
    sexo: 'Feminino',
    racaCor: 'Preta',
    situacaoVulnerabilidade: false,
    lat: -22.973774, lng: -43.284632,
    distanciaKm: 5.1,
    enderecoDescricao: '5,1 km da unidade',
    hipertenso: true, diabetico: true, gestante: false,
    condicoes: ['diabetico', 'hipertenso'],
    prioridade: 'alta', prioScore: 60,
    motivoPrioridade: 'hipertenso + diabético · 8 urgência/internação',
    ultimaVisita: '2025-12-19',
  },
  {
    id: 'p-70039a',
    nome: 'Luciana L.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '66+',
    sexo: 'Feminino',
    racaCor: 'Preta',
    situacaoVulnerabilidade: true,
    lat: -22.946399, lng: -43.260560,
    distanciaKm: 1.2,
    enderecoDescricao: '1,2 km da unidade',
    hipertenso: true, diabetico: true, gestante: false,
    condicoes: ['diabetico', 'hipertenso', 'vulneravel'],
    prioridade: 'alta', prioScore: 60,
    motivoPrioridade: 'hipertenso + diabético · idoso 66+ · vulnerável',
    ultimaVisita: '2025-11-25',
  },
  {
    id: 'p-8b5548',
    nome: 'Lucia P.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '45-65',
    sexo: 'Feminino',
    racaCor: 'Parda',
    situacaoVulnerabilidade: true,
    lat: -22.974050, lng: -43.284064,
    distanciaKm: 5.0,
    enderecoDescricao: '5,0 km da unidade',
    hipertenso: true, diabetico: true, gestante: false,
    condicoes: ['diabetico', 'hipertenso', 'vulneravel'],
    prioridade: 'alta', prioScore: 60,
    motivoPrioridade: 'hipertenso + diabético · vulnerável',
    ultimaVisita: '2025-12-06',
  },
  {
    id: 'p-ffad25',
    nome: 'Camila L.',
    equipeId: '54221d7b',
    unidadeId: 'e5870ba3',
    faixaEtaria: '66+',
    sexo: 'Feminino',
    racaCor: 'Preta',
    situacaoVulnerabilidade: true,
    lat: -22.918204, lng: -43.369271,
    distanciaKm: 12.2,
    enderecoDescricao: '12,2 km da unidade',
    hipertenso: true, diabetico: true, gestante: false,
    condicoes: ['diabetico', 'hipertenso', 'vulneravel'],
    prioridade: 'alta', prioScore: 60,
    motivoPrioridade: 'hipertenso + diabético · idoso 66+ · vulnerável',
    ultimaVisita: '2025-12-14',
  }
]

// Backward-compat: front antigo importa MOCK_PACIENTES
export const MOCK_PACIENTES = REAL_PACIENTES

export function getPacientesSemana(): Map<string, Paciente[]> {
  const hoje = new Date()
  const diaSemana = hoje.getDay()
  const seg = new Date(hoje)
  seg.setDate(hoje.getDate() - ((diaSemana === 0 ? 7 : diaSemana) - 1))

  const diasUteis = Array.from({ length: 5 }, (_, i) => {
    const d = new Date(seg)
    d.setDate(seg.getDate() + i)
    return d.toISOString().split('T')[0]
  })

  const mapa = new Map<string, Paciente[]>()
  diasUteis.forEach((dia) => mapa.set(dia, []))

  const prioOrdem = { critica: 0, alta: 1, media: 2, baixa: 3 } as const
  const ordenados = [...REAL_PACIENTES].sort((a, b) => {
    const diff = prioOrdem[a.prioridade] - prioOrdem[b.prioridade]
    return diff !== 0 ? diff : b.prioScore - a.prioScore
  })

  let diaIdx = 0
  for (const p of ordenados) {
    while (diaIdx < diasUteis.length) {
      const lista = mapa.get(diasUteis[diaIdx])!
      if (lista.length < 5) {
        lista.push(p)
        break
      }
      diaIdx++
    }
  }

  return mapa
}

export function googleMapsUrl(paciente: Paciente): string {
  return `https://www.google.com/maps/search/?api=1&query=${paciente.lat},${paciente.lng}`
}
